### ISSUE TITLE
OrderBy

### ISSUE THREAD

**Issue by kieran82** [mongodb/laravel-mongodb#2549] opened 2023-06-28 15:54 UTC
- Laravel-mongodb Version: 3.9.5
- PHP Version: 8.04
- Database Driver & Version:

### Description:
code 
TestShareUsersMongoDB::orderBy('_id', 'desc')->where('test_object_id', $this->id);

TestShareUsersMongoDB class

use Jenssegers\Mongodb\Eloquent\Model;

class TestShareUsersMongoDB extends Model

### Expected behaviour
I want to order my cosmos db query by column

### Actual behaviour
Im getting an error when i  use the orderBy that you have in your readme and i keep getting an error Trying to access array offset on value of type int. 

<details><summary><b>Logs</b>:</summary>
[2023-06-28 16:47:34] dev.ERROR: ErrorException: Trying to access array offset on value of type int in D:\GitHub\VerifactSites\portal.vfact.com\vendor\laravel\framework\src\Illuminate\Database\Query\Grammars\Grammar.php:874
Stack trace:

**Comment by GromNaN** [comment] 2023-08-28 13:37
The error comes from this line of laravel framework: https://github.com/laravel/framework/blob/v9.52.15/src/Illuminate/Database/Query/Grammars/Grammar.php#L874

I cannot reproduce this error with the provided query.

**Comment by GromNaN** [comment] 2023-08-31 14:50
Closing due to the absence of response

**Closed by GromNaN** 2023-08-31 14:50 UTC

**Comment by lechuhuuha** [comment] 2023-12-07 07:07
i have this issues 
```php
$logs = TrackingLog::where('customer_id', $customer->id);
$logs = $logs->orderBy("_id", "desc");
dump($logs->toSql());
```
three line of codes and will print out the error

mongodb version
        "mongodb/mongodb": "^1.12",
laravel version
        "laravel/framework": "^8.0",
jessenger version
        "jenssegers/mongodb": "3.8.4",
pls help
