### ISSUE TITLE
Adding typeMap in all find query because of this query taking longer time when data is large

### ISSUE THREAD

**Issue by sanjay-chabhadiya17** [mongodb/laravel-mongodb#2560] opened 2023-08-02 13:13 UTC
- Laravel-mongodb Version: "jenssegers/mongodb": "3.8"
- PHP Version: ^7.3
- Database Driver & Version: MongoDB 6.0.8

### Description:

```
db.data.find({"$and":[{"category_id":{"$in":[1,2,3,4,5,7,8,9,10,11,12,14,16,17,18,19,18775,23,24,25,26]}},{"$and":[{"price":{"$gte":1}},{"price":{"$lte":10000}},{"word_count":{"$gte":1}},{"word_count":{"$lte":10000}}]}]},{"sort":{"id":1},"skip":400,"limit":100,"typeMap":{"root":"array","document":"array"}})
```
when I'm executing above query getting result in approx 1 min.

But I have remove `typeMap":{"root":"array","document":"array"}` from query then getting result within 4-5 second. below is query.

```
db.data.find({"$and":[{"category_id":{"$in":[1,2,3,4,5,7,8,9,10,11,12,14,16,17,18,19,18775,23,24,25,26]}},{"$and":[{"price":{"$gte":1}},{"price":{"$lte":10000}},{"word_count":{"$gte":1}},{"word_count":{"$lte":10000}}]}]},{"sort":{"id":1},"skip":400,"limit":100})
```

So how we can remove this option from query?

**Comment by alcaeus** [comment] 2023-08-02 13:31
Please include the versions for laravel-mongodb, your PHP version, and the database server and driver versions in your bug report, as suggested in the issue template.

If you run the following command in the shell, how long does it take?
```js
db.data.find({"$and":[{"category_id":{"$in":[1,2,3,4,5,7,8,9,10,11,12,14,16,17,18,19,18775,23,24,25,26]}},{"$and":[{"price":{"$gte":1}},{"price":{"$lte":10000}},{"word_count":{"$gte":1}},{"word_count":{"$lte":10000}}]}]},{"sort":{"id":1},"skip":400,"limit":100}).pretty()
```

By default, the PHP library used will convert to `BSONObject` instances and `BSONArray` instances, which isn't faster by the amount you suggested. As for your question, most query methods won't allow you to configure options, and the type map shown above is set by the library itself to use objects as PHP arrays.

**Comment by sanjay-chabhadiya17** [comment] 2023-08-12 08:59
1. Laravel-mongodb Version: "jenssegers/mongodb": "3.8",
2. PHP Version: ^7.3
3. Database Driver & Version: MongoDB 6.0.8

```
db.data.find({"$and":[{"category_id":{"$in":[1,2,3,4,5,7,8,9,10,11,12,14,16,17,18,19,18775,23,24,25,26]}},{"$and":[{"price":{"$gte":1}},{"price":{"$lte":10000}},{"word_count":{"$gte":1}},{"word_count":{"$lte":10000}}]}]},{"sort":{"id":1},"skip":400,"limit":100}).pretty()
``` 

When I'm running above query result getting in 4-5 second.

**Comment by GromNaN** [comment] 2023-09-01 09:43
@alcaeus is it possible that an index on `category_id` is missing and/or there is query cache that make the 2nd execution always faster?

**Comment by alcaeus** [comment] 2023-09-06 13:50
Sorry, I lost track of this. Looking at the query, that kind of query should not this amount of time in a properly indexed database, even with a large amount of data. Even skipping 400 items and limiting to 100 means that the server would stop reading after 500 items.

Looking at this, I can spot a few potential problems:
* No index on `category_id`: this should really be the first property in an index, as you're filtering by a few categories and thus can dramatically reduce the number of documents to evaluate
* The sort is happening on the `id` field. MongoDB by default uses `_id` as primary key, and adding a separate field for an identifier breaks that assumption. If there is no index on `id`, this is going to be equally slow.
* Last but not least, `price` and `word_count` use range queries, so they can also be indexed

I would suggest reading through the [Indexing tutorial](https://www.mongodb.com/docs/v7.0/tutorial/equality-sort-range-rule/) that details the ESR (Equality, Sort, Range) rule. Based on that, the query would benefit from an compound index on the `category_id`, `id`, `price`, `word_count` fields, in that order.

**Comment by GromNaN** [comment] 2024-04-22 14:40
Closing due to the lack of details to reproduce the issue.

**Closed by GromNaN** 2024-04-22 14:40 UTC
